baseURL = "/"
languageCode = "it"
title = "Robottiamo"
theme = "hyde"

[params]
    description = "Il corso estivo di Robotica organizzato dal Liceo G. Stampacchia di Tricase"
    themeColor = "theme-base-0b"
