backend:
  name: git-gateway
  branch: master

media_folder: "static/data/uploads" # Media files will be stored in the repo under static/data/uploads
public_folder: "/data/uploads" # The src attribute for uploaded media will begin with /data/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "main"
    label: "Main"
    folder: "content/main"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Menu", name: "menu", widget: "hidden", default: "main"}
  - name: "teams"
    label: "Teams"
    folder: "content/teams"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields:
          - {label: File, name: file, widget: file}
          - {label: Name, name: name, widget: string, default: "Emmet"}

